#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 23, 2020 03:39:15 PM GMT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import entry_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = MainPage (root)
    entry_support.init(root, top)
    root.mainloop()

w = None
def create_MainPage(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_MainPage(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = MainPage (w)
    entry_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MainPage():
    global w
    w.destroy()
    w = None

class MainPage:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+899+548")
        top.minsize(120, 1)
        top.maxsize(4484, 1421)
        top.resizable(1, 1)
        top.title("MainPage")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.233, rely=0.267, relheight=0.522
                , relwidth=0.508)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.BtnLogin = tk.Button(self.Frame1)
        self.BtnLogin.place(relx=0.361, rely=0.255, height=24, width=71)
        self.BtnLogin.configure(activebackground="#ececec")
        self.BtnLogin.configure(activeforeground="#000000")
        self.BtnLogin.configure(background="#d9d9d9")
        self.BtnLogin.configure(disabledforeground="#a3a3a3")
        self.BtnLogin.configure(foreground="#000000")
        self.BtnLogin.configure(highlightbackground="#d9d9d9")
        self.BtnLogin.configure(highlightcolor="black")
        self.BtnLogin.configure(pady="0")
        self.BtnLogin.configure(text='''Login''')

        self.BtnRegister = tk.Button(self.Frame1)
        self.BtnRegister.place(relx=0.361, rely=0.596, height=24, width=73)
        self.BtnRegister.configure(activebackground="#ececec")
        self.BtnRegister.configure(activeforeground="#000000")
        self.BtnRegister.configure(background="#d9d9d9")
        self.BtnRegister.configure(disabledforeground="#a3a3a3")
        self.BtnRegister.configure(foreground="#000000")
        self.BtnRegister.configure(highlightbackground="#d9d9d9")
        self.BtnRegister.configure(highlightcolor="black")
        self.BtnRegister.configure(pady="0")
        self.BtnRegister.configure(text='''Register''')

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.267, rely=0.111, relheight=0.096
                , relwidth=0.433)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''IN3046 G23 DATABASE''')
        self.Message1.configure(width=260)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





