#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 23, 2020 03:15:53 PM GMT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import LoginPage_support

from subprocess import call


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = LoginPage (root)
    LoginPage_support.init(root, top)
    root.mainloop()

w = None
def create_LoginPage(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_LoginPage(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = LoginPage (w)
    LoginPage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_LoginPage():
    global w
    w.destroy()
    w = None

class LoginPage:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+866+602")
        top.minsize(120, 1)
        top.maxsize(4484, 1421)
        top.resizable(1, 1)
        top.title("LoginPage")
        top.configure(background="#d9d9d9")

        self.Frame = tk.Frame(top)
        self.Frame.place(relx=0.05, rely=0.067, relheight=0.856, relwidth=0.908)
        self.Frame.configure(relief='groove')
        self.Frame.configure(borderwidth="2")
        self.Frame.configure(relief="groove")
        self.Frame.configure(background="#d9d9d9")
        self.Frame.configure(cursor="fleur")

        self.Message1 = tk.Message(self.Frame)
        self.Message1.place(relx=0.202, rely=0.312, relheight=0.208
                , relwidth=0.149)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Login''')
        self.Message1.configure(width=81)

        self.Message2 = tk.Message(self.Frame)
        self.Message2.place(relx=0.22, rely=0.597, relheight=0.145
                , relwidth=0.149)
        self.Message2.configure(background="#d9d9d9")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''Password''')
        self.Message2.configure(width=81)

        self.EntryLogin = tk.Entry(self.Frame)
        self.EntryLogin.place(relx=0.385, rely=0.39,height=20, relwidth=0.429)
        self.EntryLogin.configure(background="white")
        self.EntryLogin.configure(disabledforeground="#a3a3a3")
        self.EntryLogin.configure(font="TkFixedFont")
        self.EntryLogin.configure(foreground="#000000")
        self.EntryLogin.configure(insertbackground="black")

        self.EntryPassword = tk.Entry(self.Frame)
        self.EntryPassword.place(relx=0.385, rely=0.623, height=20
                , relwidth=0.429)
        self.EntryPassword.configure(background="white")
        self.EntryPassword.configure(disabledforeground="#a3a3a3")
        self.EntryPassword.configure(font="TkFixedFont")
        self.EntryPassword.configure(foreground="#000000")
        self.EntryPassword.configure(insertbackground="black")

        self.Message3 = tk.Message(self.Frame)
        self.Message3.place(relx=0.239, rely=0.13, relheight=0.083
                , relwidth=0.567)
        self.Message3.configure(background="#d9d9d9")
        self.Message3.configure(cursor="fleur")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(text='''Welcome, please login to the database''')
        self.Message3.configure(width=309)

        self.BtnLogin = tk.Button(self.Frame)
        self.BtnLogin.place(relx=0.899, rely=0.909, height=24, width=41)
        self.BtnLogin.configure(activebackground="#ececec")
        self.BtnLogin.configure(activeforeground="#000000")
        self.BtnLogin.configure(background="#d9d9d9")
        self.BtnLogin.configure(cursor="fleur")
        self.BtnLogin.configure(disabledforeground="#a3a3a3")
        self.BtnLogin.configure(foreground="#000000")
        self.BtnLogin.configure(highlightbackground="#d9d9d9")
        self.BtnLogin.configure(highlightcolor="black")
        self.BtnLogin.configure(pady="0")
        self.BtnLogin.configure(text='''Login''')

        self.BtnBack = tk.Button(self.Frame)
        self.BtnBack.place(relx=0.018, rely=0.909, height=24, width=36)
        self.BtnBack.configure(activebackground="#ececec")
        self.BtnBack.configure(activeforeground="#000000")
        self.BtnBack.configure(background="#d9d9d9")
        self.BtnBack.configure(disabledforeground="#a3a3a3")
        self.BtnBack.configure(foreground="#000000")
        self.BtnBack.configure(highlightbackground="#d9d9d9")
        self.BtnBack.configure(highlightcolor="black")
        self.BtnBack.configure(pady="0")
        self.BtnBack.configure(text='''Back''')

if __name__ == '__main__':
    vp_start_gui()





