#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Mar 23, 2020 03:19:38 PM GMT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top64 {base} {
    global vTcl
    if {$base == ""} {
        set base .top64
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+876+581
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4484 1421
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Register"
    vTcl:DefineAlias "$top" "RegisterPage" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra65 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 425 -width 585 
    vTcl:DefineAlias "$top.fra65" "Frame1" vTcl:WidgetProc "RegisterPage" 1
    set site_3_0 $top.fra65
    message $site_3_0.mes66 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Please enter your details here} -width 340 
    vTcl:DefineAlias "$site_3_0.mes66" "Message1" vTcl:WidgetProc "RegisterPage" 1
    message $site_3_0.mes67 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Login -width 70 
    vTcl:DefineAlias "$site_3_0.mes67" "Message2" vTcl:WidgetProc "RegisterPage" 1
    message $site_3_0.mes68 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Register -width 60 
    vTcl:DefineAlias "$site_3_0.mes68" "Message3" vTcl:WidgetProc "RegisterPage" 1
    entry $site_3_0.ent69 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 214 
    vTcl:DefineAlias "$site_3_0.ent69" "Entry1" vTcl:WidgetProc "RegisterPage" 1
    entry $site_3_0.ent70 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 214 
    vTcl:DefineAlias "$site_3_0.ent70" "Entry2" vTcl:WidgetProc "RegisterPage" 1
    button $site_3_0.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Back 
    vTcl:DefineAlias "$site_3_0.but71" "BtnBack2" vTcl:WidgetProc "RegisterPage" 1
    button $site_3_0.but72 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Register 
    vTcl:DefineAlias "$site_3_0.but72" "BtnRegister" vTcl:WidgetProc "RegisterPage" 1
    place $site_3_0.mes66 \
        -in $site_3_0 -x 0 -relx 0.205 -y 0 -rely 0.071 -width 0 \
        -relwidth 0.581 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes67 \
        -in $site_3_0 -x 0 -relx 0.171 -y 0 -rely 0.353 -width 0 \
        -relwidth 0.12 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes68 \
        -in $site_3_0 -x 0 -relx 0.188 -y 0 -rely 0.541 -width 0 \
        -relwidth 0.103 -height 0 -relheight 0.054 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 0 -relx 0.359 -y 0 -rely 0.353 -width 214 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent70 \
        -in $site_3_0 -x 0 -relx 0.359 -y 0 -rely 0.541 -width 214 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but71 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.918 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but72 \
        -in $site_3_0 -x 0 -relx 0.889 -y 0 -rely 0.918 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra65 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.975 \
        -height 0 -relheight 0.944 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top64 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

