#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 23, 2020 03:19:42 PM GMT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Register_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = RegisterPage (root)
    Register_support.init(root, top)
    root.mainloop()

w = None
def create_RegisterPage(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_RegisterPage(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = RegisterPage (w)
    Register_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_RegisterPage():
    global w
    w.destroy()
    w = None

class RegisterPage:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+876+581")
        top.minsize(120, 1)
        top.maxsize(4484, 1421)
        top.resizable(1, 1)
        top.title("Register")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.017, rely=0.022, relheight=0.944
                , relwidth=0.975)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.Message1 = tk.Message(self.Frame1)
        self.Message1.place(relx=0.205, rely=0.071, relheight=0.054
                , relwidth=0.581)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Please enter your details here''')
        self.Message1.configure(width=340)

        self.Message2 = tk.Message(self.Frame1)
        self.Message2.place(relx=0.171, rely=0.353, relheight=0.054
                , relwidth=0.12)
        self.Message2.configure(background="#d9d9d9")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''Login''')
        self.Message2.configure(width=70)

        self.Message3 = tk.Message(self.Frame1)
        self.Message3.place(relx=0.188, rely=0.541, relheight=0.054
                , relwidth=0.103)
        self.Message3.configure(background="#d9d9d9")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(text='''Register''')
        self.Message3.configure(width=60)

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.359, rely=0.353,height=20, relwidth=0.366)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Entry2 = tk.Entry(self.Frame1)
        self.Entry2.place(relx=0.359, rely=0.541,height=20, relwidth=0.366)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.BtnBack2 = tk.Button(self.Frame1)
        self.BtnBack2.place(relx=0.017, rely=0.918, height=24, width=36)
        self.BtnBack2.configure(activebackground="#ececec")
        self.BtnBack2.configure(activeforeground="#000000")
        self.BtnBack2.configure(background="#d9d9d9")
        self.BtnBack2.configure(disabledforeground="#a3a3a3")
        self.BtnBack2.configure(foreground="#000000")
        self.BtnBack2.configure(highlightbackground="#d9d9d9")
        self.BtnBack2.configure(highlightcolor="black")
        self.BtnBack2.configure(pady="0")
        self.BtnBack2.configure(text='''Back''')

        self.BtnRegister = tk.Button(self.Frame1)
        self.BtnRegister.place(relx=0.889, rely=0.918, height=24, width=53)
        self.BtnRegister.configure(activebackground="#ececec")
        self.BtnRegister.configure(activeforeground="#000000")
        self.BtnRegister.configure(background="#d9d9d9")
        self.BtnRegister.configure(disabledforeground="#a3a3a3")
        self.BtnRegister.configure(foreground="#000000")
        self.BtnRegister.configure(highlightbackground="#d9d9d9")
        self.BtnRegister.configure(highlightcolor="black")
        self.BtnRegister.configure(pady="0")
        self.BtnRegister.configure(text='''Register''')

if __name__ == '__main__':
    vp_start_gui()





